# Generated by Django 4.0.6 on 2022-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0004_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
