# Generated by Django 4.0.6 on 2022-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0005_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
