# Generated by Django 4.0.6 on 2022-07-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0005_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=20, null=True)),
                ('image', models.ImageField(upload_to='post_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
