# Generated by Django 4.0.6 on 2022-07-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0006_alter_user_telephone'),
        ('appexample', '0006_image_remove_user_image'),
    ]

    operations = [
    ]
