# Generated by Django 4.0.6 on 2022-07-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0007_merge_20220728_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
