# Generated by Django 4.0.6 on 2022-07-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0010_remove_user_created_at_image_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='Me', max_length=100),
        ),
    ]
