# Generated by Django 4.0.6 on 2022-07-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0011_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
    ]
