# Generated by Django 4.0.6 on 2022-08-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0011_image_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageHost',
        ),
    ]
