# Generated by Django 4.0.6 on 2022-08-06 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0012_rename_image_imagehost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehost',
            name='uploader',
            field=models.ForeignKey(default='j', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
