# Generated by Django 4.0.6 on 2022-08-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0013_alter_imagehost_uploader'),
        ('appexample', '0013_remove_imagehost_image_imagehost_image_file_and_more'),
    ]

    operations = [
    ]
