# Generated by Django 4.1 on 2022-08-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0015_alter_imagehost_title_alter_imagehost_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resOxygen', models.FloatField()),
                ('resCarbon', models.FloatField()),
                ('eqMilesDriven', models.FloatField()),
            ],
        ),
    ]
