# Generated by Django 4.0.6 on 2022-08-09 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0015_alter_imagehost_title_alter_imagehost_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehost',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
