# Generated by Django 4.0.6 on 2022-08-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0015_alter_image_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
