# Generated by Django 4.0.6 on 2022-08-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0021_alter_image_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
    ]
