# Generated by Django 4.0.6 on 2022-08-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexample', '0026_alter_image_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
